---

- name: install common laptop packages
  pacman:
    name:
      - alacritty
      - autojump
      - bluez-tools
      - bluez-utils
      - fd
      - firefox
      - fzf
      - git
      - go
      - grim
      - imagemagick
      - imv
      - jq
      - keepassxc
      - light
      - mako
      - pavucontrol
      - podman
      - powertop
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - python
      - qt5-wayland
      - ripgrep
      - slurp
      - sudo
      - sway
      - swayidle
      - swaylock
      - tlp
      - tmux
      - tree
      - vim
      - vlc
      - waybar
      - wl-clipboard
      - zathura
      - zathura-pdf-mupdf
      - zsh
    state: present
    update_cache: "yes"

- name: copy nasskan config file
  copy:
    src: etc/nasskan/config.yaml
    dest: /etc/nasskan/config.yaml

- name: copy nasskan service
  copy:
    src: etc/systemd/system/nasskan.service
    dest: /etc/systemd/system/nasskan.service

- name: enable nasskan service
  systemd:
    name: nasskan.service
    state: started
    enabled: "yes"

- name: copy powertop service
  copy:
    src: etc/systemd/system/powertop.service
    dest: /etc/systemd/system/powertop.service

- name: enable powertop service
  systemd:
    name: powertop.service
    state: started
    enabled: "yes"

- name: copy ly config file
  copy:
    src: etc/ly/config.ini
    dest: /etc/ly/config.ini
    mode: 0644

- name: copy override file for ly service
  copy:
    src: etc/systemd/system/ly.service.d/override.conf
    dest: /etc/systemd/system/ly.service.d/override.conf

- name: enable ly service
  systemd:
    name: ly.service
    state: started
    enabled: "yes"

- name: copy sway systemd config file
  copy:
    src: etc/sway/config.d/50-systemd-user.conf
    dest: /etc/sway/config.d/50-systemd-user.conf

- name: copy subuid for podman
  copy:
    src: etc/subuid
    dest: /etc/subuid

- name: copy subgid for podman
  copy:
    src: etc/subgid
    dest: /etc/subgid
